# Sample workflow for building and deploying a Hugo site to Fleek
name: Deploy Hugo site to Fleek

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.88.1"
    - name: Build Hugo site
      run: hugo --minify
    - name: Deploy Hugo site to Fleek
      uses: felixrieseberg/fleek@v1
      with:
        fleek-token: ${{ secrets.FLEEK_TOKEN }}
        fleek-organization-id: ${{ secrets.FLEEK_ORGANIZATION_ID }}
        fleek-sites: "wiki"
        fleek-directory: "./public"
